mutual_funds/accounts/urls.py
from django.conf.urls import url

from .views import (
    ProfileDetailView, ProfileUpdateView
)


urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', ProfileDetailView.as_view(), name='profile_detail'),
    url(r'^(?P<slug>[-\w]+)/update/$', ProfileUpdateView.as_view(), name='profile_update'),
]

mutual_funds/finance/urls.py
from django.conf.urls import url

from .views import (
    MutualFundsRankingView, MSRatingView, SectorsRankingView,
    FundDetailView, SectorDetailView
)


urlpatterns = [
    url(r'^ms_rating/$', MSRatingView.as_view(), name='ms_rating'),
    url(r'^mf_ranking/$', MutualFundsRankingView.as_view(), name='mf_ranking'),
    url(r'^sectors_ranking/$', SectorsRankingView.as_view(), name='sectors_ranking'),
    url(r'^fund/(?P<slug>[-\w]+)/$', FundDetailView.as_view(), name='fund_detail'),
    url(r'^sector/(?P<slug>[-\w]+)/$', SectorDetailView.as_view(), name='sector_detail'),
]

mutual_funds/landing/urls.py
from django.conf.urls import url

from .views import (
    MainPageView, NewsDetailView, FAQView, AboutView
)

urlpatterns = [
    url(r'^$', MainPageView.as_view(), name='main_page'),
    url(r'^faq/$', FAQView.as_view(), name='faq'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^post/(?P<slug>[-\w]+)/$', NewsDetailView.as_view(), name='detail'),
]

mutual_funds/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mutual_funds.landing.urls', namespace='landing')),
    url(r'^finance/', include('mutual_funds.finance.urls', namespace='finance')),
    url(r'^auth/', include('mutual_funds.registration.backends.default.urls')),
    url(r'^accounts/', include('mutual_funds.accounts.urls', namespace='accounts')),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^api/funds/', include('mutual_funds.finance.api.urls', namespace='fund-api')),
    url(r'^api/accounts/', include('mutual_funds.accounts.api.urls', namespace='account-api')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]

mutual_funds/company/models.py
from django.db import models


class ManagementCompany(models.Model):
    name = models.CharField(max_length=320)
    slug = models.SlugField(unique=True, max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Management companies"

mutual_funds/accounts/forms.py
from django import forms
from django.forms.models import model_to_dict, fields_for_model
from django.contrib.auth.models import User
from django_countries.widgets import CountrySelectWidget
from django.utils.translation import ugettext_lazy as _

from .models import Profile


class ProfileUpdateForm(forms.ModelForm):

    def __init__(self, instance=None, *args, **kwargs):
        _fields = ('first_name', 'last_name', 'email',)
        _initial = model_to_dict(instance.user, _fields) if instance is not None else {}
        kwargs.update(initial=_initial)
        super(ProfileUpdateForm, self).__init__(instance=instance, *args, **kwargs)
        self.fields.update(fields_for_model(User, _fields))

    class Meta(object):
        model = Profile

        fields = (
            'country',
            'sex',
            'birthday',
            'avatar_thumbnail',
        )

        widgets = {
            'country': CountrySelectWidget(),
            'birthday': forms.SelectDateWidget(
                years=list(reversed(range(1901, 2002))),
                empty_label=(_("Year"), _("Month"), _("Day")),
                attrs=({'style': 'width: 32%; display: inline-block;'})),
            'avatar_thumbnail': forms.FileInput(),
            'sex': forms.RadioSelect(),
        }

    def save(self, *args, **kwargs):
        u = self.instance.user
        u.first_name = self.cleaned_data['first_name']
        u.last_name = self.cleaned_data['last_name']
        u.save()
        profile = super(ProfileUpdateForm, self).save(*args, **kwargs)
        return profile

mutual_funds/finance/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import (FinanceClass, FinanceSector)


class MutualFundsRankingForm(forms.Form):
    finance_class = forms.ModelChoiceField(
        required=False,
        queryset=FinanceClass.objects.all(),
        empty_label=_("(all classes)"),
    )
    finance_sector = forms.ModelChoiceField(
        required=False,
        queryset=FinanceSector.objects.all(),
        empty_label=_("(all sectors)"),
    )
    total_assets = forms.IntegerField(
        required=False,
        max_value=99999,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('total assets'),
                'onfocus': "this.type='number';"
            }
        )
    )
    birth_date = forms.ChoiceField(
        required=False,
        choices=[(None, _('(choose year)'))] + [(year, year) for year in reversed(range(1950, 2017))]
    )
    time_period_minimal_return = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': _('minimal return')}
        )
    )
    time_period_date = forms.ChoiceField(
        required=False,
        choices=[
            (None, _('(time period)')),
            (30, _('month')),
            (90, _('3 months')),
            (180, _('half year')),
            (1800, _('5 years'))
        ]
    )
    ms_rating = forms.ChoiceField(
        required=False,
        choices=[
            (None, _('(choose rating)')),
            (5, '5 ★ ★ ★ ★ ★ '),
            (4, '4 ★ ★ ★ ★ '),
            (3, '3 ★ ★ ★ '),
            (2, '2 ★ ★ '),
            (1, '1 ★ ')
        ]
    )

    def clean_time_period_minimal_return(self):
        time_period_minimal_return = self.cleaned_data['time_period_minimal_return']
        try:
            return float(time_period_minimal_return.replace(',', '.'))
        except:
            return False

mutual_funds/accounts/api/views.py
from django.views.generic import View
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext as _
from django.http import HttpResponse, QueryDict
from mutual_funds.utils.mixins import UserAuthenticatedAccessMixin

from mutual_funds.accounts.models import LikedFund


class ChangeLikedFundView(UserAuthenticatedAccessMixin, View):
    def put(self, request, *args, **kwargs):
        try:
            fund_id = int(QueryDict(request.body).get('fund_id'))
            LikedFund(user=request.user.profile, fund_id=fund_id).save()
            return HttpResponse("successfully liked fund")
        except Exception as e:
            return HttpResponse("some error occured")

    def delete(self, request, *args, **kwargs):
        try:
            fund_id = int(QueryDict(request.body).get('fund_id'))
            found = LikedFund.objects.get(user=request.user.profile, fund__id=fund_id)
            found.delete()
            return HttpResponse("successfully unliked fund")
        except ObjectDoesNotExist:
            return HttpResponse("some error occured")

mutual_funds/accounts/views.py
from django.http import Http404
from django.contrib import messages
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext as _

from mutual_funds.utils.mixins import UserAuthenticatedAccessMixin

from .models import Profile
from .forms import ProfileUpdateForm


class ProfileDetailView(UserAuthenticatedAccessMixin, DetailView):
    model = Profile
    template_name = 'accounts/profile.html'

    def get_object(self):
        if not Profile.objects.filter(slug=self.kwargs['slug']).exists() or self.request.user.profile != Profile.objects.get(slug=self.kwargs['slug']):
            raise Http404
        return self.get_queryset().get(slug=self.kwargs['slug'])


class ProfileUpdateView(UserAuthenticatedAccessMixin, UpdateView):
    template_name = 'accounts/update.html'
    form_class = ProfileUpdateForm

    def get_object(self):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        return context

    def get_success_url(self):
        messages.success(self.request, _('Profile updated successfully'))
        return reverse_lazy('accounts:profile_detail', kwargs={'slug': self.request.user.profile.slug})

mutual_funds/company/views.py
from django.shortcuts import render

# Create your views here.

mutual_funds/finance/api/views.py
from rest_framework.generics import RetrieveAPIView, ListAPIView
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response

from mutual_funds.finance.models import Fund

from .serialisers import FundDetailSerializer, FundListSerializer


class FundDetailAPIView(RetrieveAPIView):
    queryset = Fund.objects.published()
    serializer_class = FundDetailSerializer


class FundListAPIView(ListAPIView):
    renderer_classes = (TemplateHTMLRenderer,)
    template_name = "finance/api/list.html"
    serializer_class = FundListSerializer

    def get_queryset(self):
        queryset = Fund.objects.sort_by_return(days=self.request.query_params.get('days', 365))
        return queryset

    def get(self, request, *args, **kwargs):
        context = {
            'time_period_date': self.request.query_params.get('days', 365),
            'funds': self.get_queryset(),
        }
        return Response(context)

mutual_funds/finance/views.py
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import DetailView, TemplateView, ListView

from .models import Fund, FinanceSector
from .forms import MutualFundsRankingForm


class FundDetailView(DetailView):
    model = Fund
    template_name = 'finance/fund_detail.html'

    def get_queryset(self):
        if self.request.user.is_staff:
            return Fund.objects.all().select_related('management_company__name').prefetch_related('topfundholdings')
        else:
            return Fund.objects.published().select_related('management_company__name').prefetch_related('topfundholdings')

    def get_context_data(self, **kwargs):
        context = super(FundDetailView, self).get_context_data(**kwargs)
        return context


class MSRatingView(TemplateView):
    template_name = 'finance/ms_rating.html'

    def get_context_data(self, **kwargs):
        context = super(MSRatingView, self).get_context_data(**kwargs)
        context['funds'] = Fund.objects.published().order_by('-ms_rating').select_related('finance_sector__name')
        return context


class MutualFundsRankingView(FormMixin, ListView):
    template_name = 'finance/mutual_funds_ranking.html'
    form_class = MutualFundsRankingForm

    def check_mine(self):
        if 'mine' in self.request.GET and self.request.GET.get('mine') == 'on':
            return True
        else:
            return False

    def get_time_period_date(self):
        if 'time_period_date' in self.request.GET and self.request.GET.get('time_period_date'):
            return int(self.request.GET.get('time_period_date'))
        else:
            return False

    def get_context_data(self, **kwargs):
        context = super(MutualFundsRankingView, self).get_context_data(**kwargs)
        context['form'] = self.form_class(self.request.GET)
        context['mine'] = self.check_mine()    # only mine
        context['time_period_date'] = self.get_time_period_date()
        return context

    def get_queryset(self):
        form = self.form_class(self.request.GET)

        only_mine = self.check_mine()
        if only_mine and self.request.user.is_authenticated():
            qs = self.request.user.profile.liked_funds.published().sort_by_return().select_related('finance_sector__name')
        else:
            qs = Fund.objects.published().sort_by_return().select_related('finance_sector__name')

        if form.is_valid():
            total_assets = form.cleaned_data['total_assets']
            if total_assets is not None:
                qs = qs.filter(total_assets__gte=total_assets)

            finance_sector = form.cleaned_data['finance_sector']
            if finance_sector is not None:
                qs = qs.filter(finance_sector=finance_sector)

            birth_date = form.cleaned_data['birth_date']
            if birth_date:
                qs = qs.filter(birth_date__year__lte=birth_date)

            ms_rating = form.cleaned_data['ms_rating']
            if ms_rating:
                qs = qs.filter(ms_rating=ms_rating)

            t_period_date = form.cleaned_data['time_period_date']
            if t_period_date:
                qs = qs.sort_by_return(days=t_period_date)

            time_period_minimal_return = form.cleaned_data['time_period_minimal_return']
            if time_period_minimal_return:
                qs = qs.filter(growth__gte=time_period_minimal_return)

        return qs


class SectorsRankingView(TemplateView):
    template_name = 'finance/sectors_ranking.html'

    def check_cumulative(self):         # Cumulative View
        if 'cml' in self.request.GET:
            return True
        else:
            return False

    def check_discrete(self):           # Discrete View
        if 'dis' in self.request.GET:
            return True
        else:
            return False

    def check_usd(self):                # USD Currency
        if 'usd' in self.request.GET:
            return True
        else:
            return False

    def check_eur(self):                # EUR Currency
        if 'eur' in self.request.GET:
            return True
        else:
            return False

    def get_context_data(self, **kwargs):
        context = super(SectorsRankingView, self).get_context_data(**kwargs)
        context['sectors'] = FinanceSector.objects.published()
        context['cml'] = self.check_cumulative()    # Cumulative View
        context['dis'] = self.check_discrete()      # Discrete View
        context['usd'] = self.check_usd()           # USD Currency
        context['eur'] = self.check_eur()           # EUR Currency
        return context


class SectorDetailView(SingleObjectMixin, ListView):
    template_name = 'finance/sector_page.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=FinanceSector.objects.published())
        return super(SectorDetailView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        qs = self.object.get_funds()
        return qs

mutual_funds/landing/views.py
from django.views.generic import TemplateView, DetailView

from mutual_funds.finance.models import Fund
from .models import NewsPost


class MainPageView(TemplateView):
    template_name = 'landing/main_page.html'

    def get_context_data(self, **kwargs):
        context = super(MainPageView, self).get_context_data(**kwargs)
        context['news_posts'] = NewsPost.objects.published()
        context['funds'] = Fund.objects.sort_by_return(days=30)[:30]
        return context


class NewsDetailView(DetailView):
    model = NewsPost
    template_name = 'landing/news_page.html'

    def get_queryset(self):
        if self.request.user.is_staff:
            return NewsPost.objects.all()
        else:
            return NewsPost.objects.published()


class FAQView(TemplateView):
    template_name = 'landing/faq.html'


class AboutView(TemplateView):
    template_name = 'landing/about.html'

mutual_funds/templates/accounts/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    {{ block.super }} | {{ profile.user.get_full_name }}
{% endblock %}


{% block body %}

<div class="col-sm-12">
    <div class="btn-group pull-right m-t-15">
        <a href="{% url 'accounts:profile_update' request.user.profile.slug %}" type="button" class="btn btn-custom waves-effect waves-light">{% trans 'Edit' %} <span class="m-l-5"><i class="fa fa-cog"></i></span></a>
    </div>
    <h4 class="page-title">{% trans 'Profile' %}</h4>
</div>



<div class="row">
    <div class="col-sm-12">
        <div class="card-box profile-tab">
            <div class="dropdown pull-right">

            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="nav nav-tabs">
                        <li role="presentation" class="active">
                            <a href="#home1" role="tab" data-toggle="tab">{% trans 'Profile' %}</a>
                        </li>
                        <li>
                            <a href="{% url 'finance:mf_ranking' %}?mine=on">{% trans 'Monitor' %}</a>
                        </li>
                    </ul>
                    <div class="tab-content profile-tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="home1">
                            <div class="row">
                                <div class="col-sm-2 col-md-3 col-md-offset-1 col-lg-4 col-lg-offset-2">
                                    <div class="form-group">
                                        <img alt="" id="image_avatar" class="img-thumbnail" src="{{ profile.get_avatar }}">
                                    </div>
                                </div>




                                <div class="col-sm-10 col-md-8 col-lg-6 card-box profile-card-box">
                                    <div class="form-group">
                                        <span>{% trans 'Username' %}</span>
                                        <span class="form-control" disabled>{{ profile.user.username|default_if_none:"" }}</span>
                                    </div>

                                    <div class="form-group">
                                        <span>{% trans 'Mail' %}</span>
                                        <span class="form-control" disabled>{{ profile.user.email|default_if_none:"" }}</span>
                                    </div>

                                    <div class="row">
                                        <div class="form-group col-sm-6">
                                            <span>{% trans 'Name' %}</span>
                                            <span class="form-control" disabled>{{ profile.user.first_name|default_if_none:"" }}</span>
                                        </div>

                                        <div class="form-group col-sm-6">
                                            <span>{% trans 'Surname' %}</span>
                                            <span class="form-control" disabled>{{ profile.user.last_name|default_if_none:"" }}</span>
                                        </div>
                                    </div>

                                        
                                    <div class="form-group">
                                        <input type="radio" {% if profile.sex == 1 %}checked="checked" {% else%}disabled{% endif %}>
                                        <span>{% trans 'Man' %}</span>
                                        <input type="radio" {% if profile.sex == 0 %}checked="checked" {% else%}disabled {% endif %}>
                                        <span>{% trans 'Woman' %}</span>
                                    </div>

                                    <div class="form-group">
                                        {{ profile.birthday }}
                                    </div>


                                    <div class="form-group">
                                        {{ profile.country }}
                                    </div>


                                </div>

                            </div>
                        </div>
                        {% comment %}
                        <div role="tabpanel" class="tab-pane fade" id="profile1">
                            <div class="col-md-6">
                                <div class="profile-table-border">
                                    <table class="table">
                                    {% for fund in profile.show_liked_funds %}
                                        <tr id="{{ fund.id }}">
                                            <td>
                                                <a href="{{ fund.get_absolute_url }}" target="_blank">{{ fund.name|truncatechars:40 }}</a>
                                            </td>
                                            <td>
                                                {% csrf_token %}
                                                <a href="#" title="Delete" class="fa fa-2x fa-times pull-right edit_icons unlike_fund" aria-hidden="true"></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </table>
                                </div>
                            </div>
                            <!-- end col -->
                        </div>
                        {% endcomment %}
                    </div>
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->
        </div>
    </div>
    <!-- end col -->
</div>
<!-- end row -->

{% endblock body %}

mutual_funds/templates/accounts/update.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    {{ block.super }} | {{ profile.user.get_full_name }}
{% endblock %}


{% block body %}
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">{% trans 'Update Profile' %}</h4>
    </div>
</div>


<form method="POST" enctype="multipart/form-data" action="">{% csrf_token %}

    <div class="row">
        <div class="col-sm-2 col-md-3 col-md-offset-1 col-lg-2 col-lg-offset-2">
            <div class="form-group">
                <img alt="" id="image_avatar" class="img-thumbnail" src="{{ profile.get_avatar }}">
                <span style="display:none">{{ form.avatar_thumbnail }}</span>
            </div>
            <a id="browse" class="btn btn-block btn-warning waves-effect waves-light">{% trans 'LOAD' %}</a>
        </div>



        <div class="col-sm-10 col-md-8 col-lg-6 card-box">
            <div class="form-group">
                <span>{% trans 'Username' %}</span>
                <input type="text" class="form-control" id="id_username" maxlength="30" name="username" disabled placeholder="Ник пользователя" spellcheck="false" value="{{ profile.user.username|default_if_none:"" }}">
            </div>

            <div class="form-group">
                <span>{% trans 'Mail' %}</span>
                <input class="form-control" type="email" disabled id="id_email" maxlength="254" name="email" value="{{ profile.user.email|default_if_none:"" }}">
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <span>{% trans 'Name' %}</span>
                    <input class="form-control" type="text" id="id_first_name" maxlength="30" name="first_name" value="{{ profile.user.first_name|default_if_none:"" }}">
                </div>

                <div class="form-group col-sm-6">
                    <span>{% trans 'Surname' %}</span>
                    <input class="form-control" type="text" id="id_last_name" maxlength="30" name="last_name" value="{{ profile.user.last_name|default_if_none:"" }}">
                </div>
            </div>

                
            <div class="form-group">
                <label for="id_sex_0"><input {% if profile.sex == 1 %}checked="checked"{% endif %} id="id_sex_0" name="sex" type="radio" value="1"> {% trans 'Man' %}</label>
                <label for="id_sex_1"><input {% if profile.sex == 0 %}checked="checked"{% endif %} id="id_sex_1" name="sex" type="radio" value="0"> {% trans 'Woman' %}</label>
            </div>

            <div class="form-group">
                {{ form.birthday }}
            </div>


            <div class="form-group">
                {{ form.country }}
            </div>


            <div class="form-group">
                <button class="btn btn-purple waves-effect waves-light">{% trans 'SAVE' %}</button>
                <a href="#" onclick="javascript:history.back()" class="btn btn-primary waves-effect waves-light"><span class="zmdi zmdi-long-arrow-return"></span> {% trans 'BACK' %}</a>
            </div>
        </div>

    </div>

</form>




{% endblock body %}





{% block extra_script_base %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <script type="text/javascript">
                    toastr["warning"]("{{ error|escape }}")
                </script>
            {% endfor %}
        {% endfor %}
    {% endif %}
    <!-- Form wizard -->
    <script src="{% static 'theme/plugins/bootstrap-wizard/jquery.bootstrap.wizard.js' %}"></script>
    <script src="{% static 'theme/plugins/jquery-validation/dist/jquery.validate.min.js' %}"></script>
{% endblock extra_script_base %}



{% block page_script_base %}
    {{ block.super }}
    <script type="text/javascript">
    $('#browse').click(function(){
        $(this).parent().find('input').click();
    });

      $( function() {
        $( document ).tooltip();
      } );
        document.getElementById("id_avatar_thumbnail").onchange = function () {
        var reader = new FileReader();
        reader.onload = function (e) {
            // get loaded data and render thumbnail.
            document.getElementById("image_avatar").src = e.target.result;
        };

        // read the image file as a data URL.
        reader.readAsDataURL(this.files[0]);
    };

    </script>
{% endblock page_script_base %}