mutual_funds/accounts/urls.py
from django.conf.urls import url

from .views import (
    ProfileDetailView, ProfileUpdateView
)


urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', ProfileDetailView.as_view(), name='profile_detail'),
    url(r'^(?P<slug>[-\w]+)/update/$', ProfileUpdateView.as_view(), name='profile_update'),
]

mutual_funds/finance/api/urls.py
from django.conf.urls import url

from .views import (
    FundDetailAPIView, FundListAPIView
)


urlpatterns = [
    url(r'^$', FundListAPIView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', FundDetailAPIView.as_view(), name='detail'),
]

mutual_funds/finance/urls.py
from django.conf.urls import url

from .views import (
    MutualFundsRankingView, MSRatingView, SectorsRankingView,
    FundDetailView, SectorDetailView
)


urlpatterns = [
    url(r'^ms_rating/$', MSRatingView.as_view(), name='ms_rating'),
    url(r'^mf_ranking/$', MutualFundsRankingView.as_view(), name='mf_ranking'),
    url(r'^sectors_ranking/$', SectorsRankingView.as_view(), name='sectors_ranking'),
    url(r'^fund/(?P<slug>[-\w]+)/$', FundDetailView.as_view(), name='fund_detail'),
    url(r'^sector/(?P<slug>[-\w]+)/$', SectorDetailView.as_view(), name='sector_detail'),
]

mutual_funds/landing/urls.py
from django.conf.urls import url

from .views import (
    MainPageView, NewsDetailView, FAQView, AboutView
)

urlpatterns = [
    url(r'^$', MainPageView.as_view(), name='main_page'),
    url(r'^faq/$', FAQView.as_view(), name='faq'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^post/(?P<slug>[-\w]+)/$', NewsDetailView.as_view(), name='detail'),
]

mutual_funds/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mutual_funds.landing.urls', namespace='landing')),
    url(r'^finance/', include('mutual_funds.finance.urls', namespace='finance')),
    url(r'^auth/', include('mutual_funds.registration.backends.default.urls')),
    url(r'^accounts/', include('mutual_funds.accounts.urls', namespace='accounts')),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^api/funds/', include('mutual_funds.finance.api.urls', namespace='fund-api')),
    url(r'^api/accounts/', include('mutual_funds.accounts.api.urls', namespace='account-api')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]

mutual_funds/company/models.py
from django.db import models


class ManagementCompany(models.Model):
    name = models.CharField(max_length=320)
    slug = models.SlugField(unique=True, max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Management companies"

mutual_funds/accounts/forms.py
from django import forms
from django.forms.models import model_to_dict, fields_for_model
from django.contrib.auth.models import User
from django_countries.widgets import CountrySelectWidget
from django.utils.translation import ugettext_lazy as _

from .models import Profile


class ProfileUpdateForm(forms.ModelForm):

    def __init__(self, instance=None, *args, **kwargs):
        _fields = ('first_name', 'last_name', 'email',)
        _initial = model_to_dict(instance.user, _fields) if instance is not None else {}
        kwargs.update(initial=_initial)
        super(ProfileUpdateForm, self).__init__(instance=instance, *args, **kwargs)
        self.fields.update(fields_for_model(User, _fields))

    class Meta(object):
        model = Profile

        fields = (
            'country',
            'sex',
            'birthday',
            'avatar_thumbnail',
        )

        widgets = {
            'country': CountrySelectWidget(),
            'birthday': forms.SelectDateWidget(
                years=list(reversed(range(1901, 2002))),
                empty_label=(_("Year"), _("Month"), _("Day")),
                attrs=({'style': 'width: 32%; display: inline-block;'})),
            'avatar_thumbnail': forms.FileInput(),
            'sex': forms.RadioSelect(),
        }

    def save(self, *args, **kwargs):
        u = self.instance.user
        u.first_name = self.cleaned_data['first_name']
        u.last_name = self.cleaned_data['last_name']
        u.save()
        profile = super(ProfileUpdateForm, self).save(*args, **kwargs)
        return profile

mutual_funds/finance/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import (FinanceClass, FinanceSector)


class MutualFundsRankingForm(forms.Form):
    finance_class = forms.ModelChoiceField(
        required=False,
        queryset=FinanceClass.objects.all(),
        empty_label=_("(all classes)"),
    )
    finance_sector = forms.ModelChoiceField(
        required=False,
        queryset=FinanceSector.objects.all(),
        empty_label=_("(all sectors)"),
    )
    total_assets = forms.IntegerField(
        required=False,
        max_value=99999,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('total assets'),
                'onfocus': "this.type='number';"
            }
        )
    )
    birth_date = forms.ChoiceField(
        required=False,
        choices=[(None, _('(choose year)'))] + [(year, year) for year in reversed(range(1950, 2017))]
    )
    time_period_minimal_return = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': _('minimal return')}
        )
    )
    time_period_date = forms.ChoiceField(
        required=False,
        choices=[
            (None, _('(time period)')),
            (30, _('month')),
            (90, _('3 months')),
            (180, _('half year')),
            (1800, _('5 years'))
        ]
    )
    ms_rating = forms.ChoiceField(
        required=False,
        choices=[
            (None, _('(choose rating)')),
            (5, '5 ★ ★ ★ ★ ★ '),
            (4, '4 ★ ★ ★ ★ '),
            (3, '3 ★ ★ ★ '),
            (2, '2 ★ ★ '),
            (1, '1 ★ ')
        ]
    )

    def clean_time_period_minimal_return(self):
        time_period_minimal_return = self.cleaned_data['time_period_minimal_return']
        try:
            return float(time_period_minimal_return.replace(',', '.'))
        except:
            return False

mutual_funds/accounts/api/views.py
from django.views.generic import View
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext as _
from django.http import HttpResponse, QueryDict
from mutual_funds.utils.mixins import UserAuthenticatedAccessMixin

from mutual_funds.accounts.models import LikedFund


class ChangeLikedFundView(UserAuthenticatedAccessMixin, View):
    def put(self, request, *args, **kwargs):
        try:
            fund_id = int(QueryDict(request.body).get('fund_id'))
            LikedFund(user=request.user.profile, fund_id=fund_id).save()
            return HttpResponse("successfully liked fund")
        except Exception as e:
            return HttpResponse("some error occured")

    def delete(self, request, *args, **kwargs):
        try:
            fund_id = int(QueryDict(request.body).get('fund_id'))
            found = LikedFund.objects.get(user=request.user.profile, fund__id=fund_id)
            found.delete()
            return HttpResponse("successfully unliked fund")
        except ObjectDoesNotExist:
            return HttpResponse("some error occured")

mutual_funds/accounts/views.py
from django.http import Http404
from django.contrib import messages
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext as _

from mutual_funds.utils.mixins import UserAuthenticatedAccessMixin

from .models import Profile
from .forms import ProfileUpdateForm


class ProfileDetailView(UserAuthenticatedAccessMixin, DetailView):
    model = Profile
    template_name = 'accounts/profile.html'

    def get_object(self):
        if not Profile.objects.filter(slug=self.kwargs['slug']).exists() or self.request.user.profile != Profile.objects.get(slug=self.kwargs['slug']):
            raise Http404
        return self.get_queryset().get(slug=self.kwargs['slug'])


class ProfileUpdateView(UserAuthenticatedAccessMixin, UpdateView):
    template_name = 'accounts/update.html'
    form_class = ProfileUpdateForm

    def get_object(self):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        return context

    def get_success_url(self):
        messages.success(self.request, _('Profile updated successfully'))
        return reverse_lazy('accounts:profile_detail', kwargs={'slug': self.request.user.profile.slug})

mutual_funds/company/views.py
from django.shortcuts import render

# Create your views here.

mutual_funds/finance/api/views.py
from rest_framework.generics import RetrieveAPIView, ListAPIView
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response

from mutual_funds.finance.models import Fund

from .serialisers import FundDetailSerializer, FundListSerializer


class FundDetailAPIView(RetrieveAPIView):
    queryset = Fund.objects.published()
    serializer_class = FundDetailSerializer


class FundListAPIView(ListAPIView):
    renderer_classes = (TemplateHTMLRenderer,)
    template_name = "finance/api/list.html"
    serializer_class = FundListSerializer

    def get_queryset(self):
        queryset = Fund.objects.sort_by_return(days=self.request.query_params.get('days', 365))
        return queryset

    def get(self, request, *args, **kwargs):
        context = {
            'time_period_date': self.request.query_params.get('days', 365),
            'funds': self.get_queryset(),
        }
        return Response(context)

mutual_funds/finance/views.py
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import DetailView, TemplateView, ListView

from .models import Fund, FinanceSector
from .forms import MutualFundsRankingForm


class FundDetailView(DetailView):
    model = Fund
    template_name = 'finance/fund_detail.html'

    def get_queryset(self):
        if self.request.user.is_staff:
            return Fund.objects.all().select_related('management_company__name').prefetch_related('topfundholdings')
        else:
            return Fund.objects.published().select_related('management_company__name').prefetch_related('topfundholdings')

    def get_context_data(self, **kwargs):
        context = super(FundDetailView, self).get_context_data(**kwargs)
        return context


class MSRatingView(TemplateView):
    template_name = 'finance/ms_rating.html'

    def get_context_data(self, **kwargs):
        context = super(MSRatingView, self).get_context_data(**kwargs)
        context['funds'] = Fund.objects.published().order_by('-ms_rating').select_related('finance_sector__name')
        return context


class MutualFundsRankingView(FormMixin, ListView):
    template_name = 'finance/mutual_funds_ranking.html'
    form_class = MutualFundsRankingForm

    def check_mine(self):
        if 'mine' in self.request.GET and self.request.GET.get('mine') == 'on':
            return True
        else:
            return False

    def get_time_period_date(self):
        if 'time_period_date' in self.request.GET and self.request.GET.get('time_period_date'):
            return int(self.request.GET.get('time_period_date'))
        else:
            return False

    def get_context_data(self, **kwargs):
        context = super(MutualFundsRankingView, self).get_context_data(**kwargs)
        context['form'] = self.form_class(self.request.GET)
        context['mine'] = self.check_mine()    # only mine
        context['time_period_date'] = self.get_time_period_date()
        return context

    def get_queryset(self):
        form = self.form_class(self.request.GET)

        only_mine = self.check_mine()
        if only_mine and self.request.user.is_authenticated():
            qs = self.request.user.profile.liked_funds.published().sort_by_return().select_related('finance_sector__name')
        else:
            qs = Fund.objects.published().sort_by_return().select_related('finance_sector__name')

        if form.is_valid():
            total_assets = form.cleaned_data['total_assets']
            if total_assets is not None:
                qs = qs.filter(total_assets__gte=total_assets)

            finance_sector = form.cleaned_data['finance_sector']
            if finance_sector is not None:
                qs = qs.filter(finance_sector=finance_sector)

            birth_date = form.cleaned_data['birth_date']
            if birth_date:
                qs = qs.filter(birth_date__year__lte=birth_date)

            ms_rating = form.cleaned_data['ms_rating']
            if ms_rating:
                qs = qs.filter(ms_rating=ms_rating)

            t_period_date = form.cleaned_data['time_period_date']
            if t_period_date:
                qs = qs.sort_by_return(days=t_period_date)

            time_period_minimal_return = form.cleaned_data['time_period_minimal_return']
            if time_period_minimal_return:
                qs = qs.filter(growth__gte=time_period_minimal_return)

        return qs


class SectorsRankingView(TemplateView):
    template_name = 'finance/sectors_ranking.html'

    def check_cumulative(self):         # Cumulative View
        if 'cml' in self.request.GET:
            return True
        else:
            return False

    def check_discrete(self):           # Discrete View
        if 'dis' in self.request.GET:
            return True
        else:
            return False

    def check_usd(self):                # USD Currency
        if 'usd' in self.request.GET:
            return True
        else:
            return False

    def check_eur(self):                # EUR Currency
        if 'eur' in self.request.GET:
            return True
        else:
            return False

    def get_context_data(self, **kwargs):
        context = super(SectorsRankingView, self).get_context_data(**kwargs)
        context['sectors'] = FinanceSector.objects.published()
        context['cml'] = self.check_cumulative()    # Cumulative View
        context['dis'] = self.check_discrete()      # Discrete View
        context['usd'] = self.check_usd()           # USD Currency
        context['eur'] = self.check_eur()           # EUR Currency
        return context


class SectorDetailView(SingleObjectMixin, ListView):
    template_name = 'finance/sector_page.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=FinanceSector.objects.published())
        return super(SectorDetailView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        qs = self.object.get_funds()
        return qs

mutual_funds/landing/views.py
from django.views.generic import TemplateView, DetailView

from mutual_funds.finance.models import Fund
from .models import NewsPost


class MainPageView(TemplateView):
    template_name = 'landing/main_page.html'

    def get_context_data(self, **kwargs):
        context = super(MainPageView, self).get_context_data(**kwargs)
        context['news_posts'] = NewsPost.objects.published()
        context['funds'] = Fund.objects.sort_by_return(days=30)[:30]
        return context


class NewsDetailView(DetailView):
    model = NewsPost
    template_name = 'landing/news_page.html'

    def get_queryset(self):
        if self.request.user.is_staff:
            return NewsPost.objects.all()
        else:
            return NewsPost.objects.published()


class FAQView(TemplateView):
    template_name = 'landing/faq.html'


class AboutView(TemplateView):
    template_name = 'landing/about.html'

mutual_funds/templates/landing/about.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    {{ block.super }} | {% trans 'About' %}
{% endblock %}



{% block body %}

<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">{% trans 'About' %}</h4>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <!-- <div class="panel-heading">
                                <h4>Invoice</h4>
                            </div> -->
            <div class="panel-body">
                <div class="clearfix">
                    <div class="pull-left">
                        <h3 class="logo invoice-logo">Fundexpert</h3>
                    </div>
                    <div class="pull-right">
                        <h4>Some about info<br>
                                            <strong>Created: 02-01-1998</strong>
                                        </h4>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-12">

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-9 col-sm-9 col-xs-9">
                        <div class="clearfix">
                            <h5 class="small text-inverse font-600">Our company bla bla ...</h5>
                            <small>
                                                

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas porttitor nibh magna, vitae accumsan nibh congue nec. Integer consequat nec nisi id laoreet. Curabitur tellus massa, ultrices sed dui non, luctus finibus augue. Mauris at luctus libero, non luctus augue. Nulla auctor, felis quis laoreet semper, lorem ipsum euismod lacus, non tincidunt purus est a sapien. Aenean varius arcu sed diam sagittis euismod. Cras id aliquam turpis. Pellentesque egestas arcu nec euismod tincidunt. Suspendisse felis diam, sodales sit amet metus rhoncus, blandit egestas urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae turpis varius odio pretium pretium vel vel enim. Etiam sit amet eros ultricies massa vestibulum maximus. Cras eleifend leo a tellus vulputate imperdiet. Cras mollis sit amet sapien eu sollicitudin. Curabitur ac tincidunt nisl, non hendrerit orci. Etiam a venenatis neque, vitae scelerisque elit.

Aliquam maximus sapien velit, ut pulvinar enim molestie ut. Nunc finibus lorem id ornare bibendum. Vestibulum feugiat lorem mauris, sed maximus leo mollis eu. Curabitur blandit dui ut orci condimentum volutpat. Ut elit nunc, volutpat sit amet erat in, egestas congue augue. Donec non hendrerit quam. Praesent a mollis dolor, at ornare urna. Curabitur et maximus turpis. Vivamus vel ornare lorem, nec fermentum massa. Duis viverra vel purus ac porta. Proin sit amet leo at libero sagittis imperdiet gravida vitae magna. Nunc non pretium purus, sed lacinia dolor. Morbi gravida convallis purus, eu mollis urna. Suspendisse porttitor ornare erat, a tempor eros aliquet nec.

Nam in risus vitae metus auctor vehicula a vitae est. Fusce varius in risus a rhoncus. Vivamus laoreet consequat risus et egestas. Sed pharetra, purus ullamcorper ullamcorper ultricies, diam risus mollis ligula, non malesuada felis nibh non velit. Nunc ex lectus, tempus sed dapibus at, consequat at justo. Duis malesuada ipsum sit amet lacus maximus, vel porta enim pharetra. Proin malesuada mollis ligula eget lobortis. Aliquam gravida tellus velit, non placerat purus pellentesque in. Donec malesuada tempor pulvinar. Sed nec nisi vitae nisl porttitor dictum viverra volutpat purus. Donec lacinia scelerisque turpis, quis iaculis nunc faucibus sed. Praesent ut est sed felis cursus efficitur. Maecenas a varius nisl, id molestie dolor. Donec efficitur hendrerit enim, a posuere enim dapibus vitae.

Nulla dapibus ante non nibh efficitur tempus. Duis et velit eget turpis pretium gravida sit amet id dui. Vivamus efficitur dictum orci, eu pretium arcu. Donec volutpat quam lacinia porttitor sodales. Vestibulum sagittis dignissim ultricies. Sed volutpat at massa eu semper. Etiam eros magna, venenatis a iaculis non, pulvinar euismod arcu. Nulla iaculis mi sit amet arcu faucibus elementum. Curabitur tempus elit leo, vitae facilisis quam auctor in. Donec at urna justo.

Etiam nec vehicula nisl. Maecenas sollicitudin feugiat bibendum. Fusce fringilla, nunc sit amet bibendum posuere, massa ex pellentesque quam, sed fermentum felis quam et magna. In quis turpis aliquet est ornare ornare. Sed tempus dapibus nunc, eget scelerisque ligula commodo vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus et consectetur dui, vitae volutpat lectus. 
                                            </small>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <p class="text-right"><b>Here valuable info:</b> some year</p>
                        <p class="text-right">Discout: 12.9%</p>
                        <p class="text-right">VAT: 12.9%</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->



{% endblock body %}

mutual_funds/templates/landing/main_page.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load imagekit %}


{% block head_extra_css %}
<!-- responsive table css -->
<link href="{% static 'theme/plugins/RWD-Table-Patterns/dist/css/rwd-table.min.css' %}" rel="stylesheet" type="text/css" media="screen">
{% endblock %}


{% block head_page_style %}
<link href="{% static 'landing/css/landing.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}


{% block body %}

<div class="row">
    <div class="col-sm-8 col-lg-7 col-lg-offset-1">
        <h2 class="page-title">{% trans 'News' %}</h2>
        <div class="card-box">

            {% for post in news_posts %}
                <hr class="featurette-divider">
                <div class="row featurette post_list news-object" onclick="window.location = '{{ post.get_absolute_url }}'">
                    <div class="col-sm-7 col-sm-push-5 right-text">
                        <a href='{{ post.get_absolute_url }}'><h2 class="a2 mylead news-header">{{ post.title|truncatechars:30 }}</h2>
                        </a>
                        <div class="post-detail-item news-description">
                            {{ post.text|safe|truncatechars_html:120 }}
                            <button type="button" onclick="window.location = '{{ post.get_absolute_url }}'" class="btn btn-default">{% trans 'Read more' %} &rarr;</button>
                        </div>
                    </div>

                    <div class="col-sm-5 col-sm-pull-7 left-image-col hidden-xs">
                        <img class="featurette-image img-responsive center-block left-image"
                            src="{{ post.image_thumbnail.url }}" alt="">
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="col-sm-4 col-lg-4 pull-right hidden-xs">
        {% include 'includes/base_indexes.html' %}
    </div>


</div>



<div class="row">
    <div class="col-sm-12 col-md-12">
        <h4 class="page-title">{% trans 'Best 30 MFs' %}</h4>
        <div class="card-box">
            <div class="table-rep-plugin">
                
                <div class="btn-group m-b-10" data-toggle="buttons">
                  <label class="btn btn-default active">
                    <input type="radio" class="load_radio" data-days="30" name="options" id="option1" checked>{% trans '30 days' %}
                  </label>
                  <label class="btn btn-default">
                    <input type="radio" class="load_radio" data-days="60" name="options" id="option2"> {% trans '60 days' %}
                  </label>
                  <label class="btn btn-default">
                    <input type="radio" class="load_radio" data-days="90" name="options" id="option3"> {% trans '90 days' %}
                  </label>
                </div>
                        
                <div class="table-responsive">
                    <table id="landing_datatable" class="table  table-striped">
                    {% include 'finance/api/list.html' %}
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock body %}


{% block page_script_base %}
{% include 'includes/likes_js.html' %}
{% endblock page_script_base %}



{% block extra_script_base %}
<!-- Responsive Datatables-->
<script src="{% static 'theme/plugins/RWD-Table-Patterns/dist/js/rwd-table.min.js' %}"></script>

<script type="text/javascript">

$(".load_radio").on("change", function() {
    days = parseInt($(this).data("days"));
    $.ajax({
        url:"{% url 'fund-api:list' %}",
        type: 'GET',
        data: {'days': days},
        dataType: 'HTML',
        success: function(data){
            $('#landing_datatable').html(data);
            // reseting listeners and restarting them
            {% if request.user.is_authenticated %}
                setLikes();
            {% endif %}
        }
    });
});
</script>
{% endblock %}

mutual_funds/templates/landing/news_page.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    {{ block.super }} | {{ newspost.title|truncatechars:10 }}
{% endblock %}



{% block head_page_style %}
<link href="{% static 'landing/css/landing.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}



{% block body %}


<div class="row">
    <div class="col-sm-8">
    <h2 class="page-title">{{ newspost.title }}</h2>
        

        <img class="featurette-image img-responsive news_post" src="{{ newspost.image.url }}">

        <div class="card-box">

        {{ newspost.text|safe }}
        </div>
    </div>

    <div class="col-sm-4">

    {% include 'includes/base_indexes.html' %}

        <h4 class="page-title">{% trans 'Other news' %}</h4>
        
        {% for other_new in newspost.get_latest_news %}
        <div class="gal-detail thumb other_new">
            <a href="{{ other_new.get_absolute_url }}" class="image-popup" title="Screenshot-1">
                <img src="{{ other_new.image_thumbnail.url }}" class="thumb-img" alt="work-thumbnail">
            </a>
            <h4>{{ other_new.title|truncatechars:30 }}</h4>
            <p class="text-muted">{{ other_new.text|safe|truncatechars_html:170 }}</p>
        </div>
        {% endfor %}

    </div>

</div>
{% endblock body %}